version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: ambaal_mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ambaal_shop

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: ambaal_app

    restart: always

    depends_on:
      - mysql

    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ambaal_shop
      SECRET_KEY: my-secret-key

    ports:
      - "5003:5003"

volumes:
  mysql_data: