services:
  mysql:
    image: mysql:8.0
    container_name: ambaal_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ambaal_shop

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  app:
    image: viththi/viththi_arul:latest
    container_name: ambaal_app
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ambaal_shop
      SECRET_KEY: ambaal-shop-secret-key

    ports:
      - "5003:5003"

volumes:
  mysql_data: